
name: Deploy

on:
  push:
    branches: [main]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: frontend
      uses: actions/checkout@v2


    - name: Set up node:lts-alpine environment
      uses: actions/setup-node@v3
    - name: frontend Run
      run: |
        cd frontend
        npm i 
        npm run build
    
    - name: backend
      uses: actions/checkout@v2


    - name: backend Run
      run: |
        cd backend
        npm i 
        npm start
    
  